name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova & cordova-res
      run: |
        npm install -g cordova
        npm install -g cordova-res

    - name: Create Cordova Project
      run: |
        cordova create trainerApp com.htmltrainer.app "HTML Trainer"
        cp -r ./ trainerApp/www/
        cd trainerApp
        cordova platform add android

    - name: Add App Icon & Splash
      run: |
        cd trainerApp
        mkdir -p resources
        # ضع أيقونتك هنا
        cp ../icon.png resources/icon.png
        # توليد أيقونات وشاشات تلقائياً
        cordova-res android --skip-config --copy

    - name: Build Android APK
      run: |
        cd trainerApp
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: html-trainer-apk
        path: trainerApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
